# Generated by Django 5.1.7 on 2025-04-07 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_rename_airline_flight_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='departure',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='name',
        ),
        migrations.AddField(
            model_name='flight',
            name='arrival_city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_city',
            field=models.CharField(default='Unknown City', max_length=100),
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_class',
            field=models.CharField(choices=[('economy', 'Economy'), ('business', 'Business'), ('first', 'First Class')], default='economy', max_length=20),
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(default='UNKNOWN123', max_length=10),
        ),
        migrations.AddField(
            model_name='flight',
            name='is_direct',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
